export default function zoneData(state = {}, action) {
	var data = [
		{
			"x":1,
			"y":1,
			"width":9,
			"height":9,
			"color":"white",
			"name":"z1",
			"activeTag":[],
			"strokeColor":"black"
		},{
			"x":10,
			"y":1,
			"width":9,
			"height":9,
			"color":"white",
			"name":"z2",
			"activeTag":[],
			"strokeColor":"black"
		},{
			"x":19,
			"y":1,
			"width":9,
			"height":9,
			"color":"white",
			"name":"z3",
			"activeTag":[],
			"strokeColor":"black"
		},{
			"x":1,
			"y":10,
			"width":9,
			"height":9,
			"color":"white",
			"name":"z4",
			"activeTag":[],
			"strokeColor":"black"
		},{
			"x":10,
			"y":10,
			"width":9,
			"height":9,
			"color":"white",
			"name":"z5",
			"activeTag":[],
			"strokeColor":"black"
		},{
			"x":19,
			"y":10,
			"width":9,
			"height":9,
			"color":"white",
			"name":"z6",
			"activeTag":[],
			"strokeColor":"black"
		},{
			"x":1,
			"y":19,
			"width":9,
			"height":9,
			"color":"white",
			"name":"z7",
			"activeTag":[],
			"strokeColor":"black"
		},{
			"x":10,
			"y":19,
			"width":9,
			"height":9,
			"color":"white",
			"name":"z8",
			"activeTag":[],
			"strokeColor":"black"
		},{
			"x":19,
			"y":19,
			"width":9,
			"height":9,
			"color":"white",
			"name":"z9",
			"activeTag":[],
			"strokeColor":"black"
		},{
			"x":1,
			"y":28,
			"width":9,
			"height":9,
			"color":"white",
			"name":"z10",
			"activeTag":[],
			"strokeColor":"black"
		},{
			"x":10,
			"y":28,
			"width":9,
			"height":9,
			"color":"white",
			"name":"z11",
			"activeTag":[],
			"strokeColor":"black"
		},{
			"x":19,
			"y":28,
			"width":9,
			"height":9,
			"color":"white",
			"name":"z12",
			"activeTag":[],
			"strokeColor":"black"
		}
	];
	return data;
}